service: reverse-mac
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
functions:
  reverse_mac:
    handler: handler.reverseMac
    events:
      - http:
          path: reverse_mac
          method: post
          authorizer:
            name: tokenAuthorizer
  tokenAuthorizer:
    handler: handler.authorize
plugins:
  - serverless-offline
